name: Fetch GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:


jobs:

  fetch:

    runs-on: ubuntu-latest

    permissions:
      contents: write


    steps:

      - uses: actions/checkout@v4


      - name: Fetch Stats

        run: |

          curl -L \
          "https://github-readme-stats-r4ol293mc-thefoolyuzhe-5613s-projects.vercel.app/api?username=YUZHEthefool&show_icons=true&include_all_commits=true&theme=tokyonight&hide_border=true" \
          -o github-stats.svg



      - name: Fix SVG XML

        run: |

          python3 << 'EOF'

          from pathlib import Path

          p = Path("github-stats.svg")

          data = p.read_text()

          # 修复裸 &
          data = data.replace("& ", "&amp; ")

          p.write_text(data)

          EOF



      - name: Commit

        run: |

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add github-stats.svg

          git commit -m "Update github stats" || exit 0

          git push
