name: GitHub-Profile-3D-Contrib

on:
  # 每天的 00:00 UTC 时间运行
  schedule:
    - cron: "0 0 * * *"
  # 允许你手动从 Actions 标签页运行此工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
